const commonFaq = {
  ms: [
    { q: "Berapa lama kerja epoxy biasanya siap?", a: "Kebanyakan ruang kecil mengambil sekitar 2–3 hari. Tempoh sebenar ikut saiz, keadaan lantai dan sistem yang dipilih." },
    { q: "Boleh terus apply atas jubin lama?", a: "Bergantung pada keadaan jubin. Kami check jubin longgar, kelembapan dan lekatan sebelum cadangkan preparation yang sesuai." }
  ],
  en: [
    { q: "How long does epoxy installation usually take?", a: "Most small spaces take around 2–3 days. Actual timing depends on size, floor condition and the selected system." },
    { q: "Can epoxy be applied over old tiles?", a: "It depends on the tile condition. We inspect loose tiles, moisture and adhesion before recommending the preparation method." }
  ],
  zh: [
    { q: "环氧地坪施工通常需要几天？", a: "多数小空间约需 2–3 天。实际时间取决于面积、地面情况和所选系统。" },
    { q: "可以直接在旧瓷砖上施工吗？", a: "要看瓷砖情况。我们会检查松动、湿度和附着条件，再建议合适的地面处理方法。" }
  ]
};

export const seoPages = {
  "epoxy-flooring-kota-kinabalu": {
    slug: "epoxy-flooring-kota-kinabalu", area: "Kota Kinabalu, Sabah", metaTitle: "Epoxy Flooring Kota Kinabalu | FLEKS Epoxy Sabah", metaDescription: "Servis epoxy flooring di Kota Kinabalu untuk rumah, bilik air, garage, kedai, showroom dan ruang komersial. Lawatan tapak percuma.",
    content: {
      ms: { h1: "Epoxy Flooring Kota Kinabalu untuk Rumah & Komersial", intro: "Untuk lantai lama yang licin, berbekas atau susah dicuci di sekitar Kota Kinabalu, FLEKS akan check permukaan dulu sebelum cadangkan sistem epoxy. Servis sesuai untuk rumah, bilik air, garage, kedai, showroom dan ruang komersial.", problemsTitle: "Masalah lantai yang biasa kami jumpa di KK", problems: ["Jubin bilik air licin dan grout susah dicuci", "Lantai garage ada kesan minyak atau kotoran", "Lantai kedai kusam selepas penggunaan harian", "Permukaan lama retak, lembap atau tidak rata"], systemTitle: "Sistem yang kami cadangkan", system: "Epoxy flake sesuai untuk ruang yang perlukan tekstur dan pilihan anti-slip. Untuk showroom atau ruang dalaman, kemasan solid atau metallic boleh dipertimbangkan selepas keadaan lantai diperiksa.", price: "Anggaran biasa RM28–RM32/kps. Harga akhir bergantung pada saiz, surface preparation, repair dan finishing.", faq: [{ q: "Kawasan mana di Kota Kinabalu yang FLEKS cover?", a: "Kami cover Kota Kinabalu dan kawasan sekitar seperti Likas, Inanam, Penampang dan Putatan. Hubungi kami untuk semak lokasi projek." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring in Kota Kinabalu for Homes & Commercial Spaces", intro: "For old floors in Kota Kinabalu that are slippery, stained or difficult to clean, FLEKS inspects the surface before recommending an epoxy system. We cover homes, bathrooms, garages, shops, showrooms and commercial spaces.", problemsTitle: "Common floor problems in Kota Kinabalu", problems: ["Slippery bathroom tiles and difficult grout lines", "Oil marks and stains on garage floors", "Dull shop floors from daily use", "Cracked, damp or uneven existing surfaces"], systemTitle: "Recommended epoxy systems", system: "Epoxy flake works well where texture and an anti-slip option are needed. Solid or metallic finishes may suit showrooms and interiors after the floor has been inspected.", price: "Typical estimate: RM28–RM32/sqft. Final pricing depends on size, preparation, repairs and finish.", faq: [{ q: "Which Kota Kinabalu areas does FLEKS cover?", a: "We cover Kota Kinabalu and nearby areas including Likas, Inanam, Penampang and Putatan. Contact us to confirm your project location." }, ...commonFaq.en] },
      zh: { h1: "Kota Kinabalu 住宅与商业环氧地坪", intro: "如果 Kota Kinabalu 的旧地面太滑、有污渍或难以清理，FLEKS 会先检查表面，再建议合适的环氧地坪系统。服务范围包括住宅、浴室、车库、店铺、展厅和商业空间。", problemsTitle: "Kota Kinabalu 常见地面问题", problems: ["浴室瓷砖打滑，砖缝难清理", "车库地面有油污和痕迹", "店铺地面因日常使用而暗淡", "旧地面开裂、潮湿或不平"], systemTitle: "建议的环氧系统", system: "需要纹理和防滑选择的空间可考虑环氧彩片。展厅和室内空间可在检查地面后选择纯色或金属效果。", price: "一般估价约 RM28–RM32/平方尺。最终价格取决于面积、地面处理、修补和效果。", faq: [{ q: "FLEKS 服务 Kota Kinabalu 哪些地区？", a: "我们服务 Kota Kinabalu 以及 Likas、Inanam、Penampang 和 Putatan 等周边地区。可联系我们确认项目地点。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flooring-penampang": {
    slug: "epoxy-flooring-penampang", area: "Penampang, Sabah", metaTitle: "Epoxy Flooring Penampang | FLEKS Epoxy Sabah", metaDescription: "Epoxy flooring di Penampang untuk rumah teres, bilik air, dapur dan garage. Pilihan anti-slip dan lawatan tapak percuma.",
    content: {
      ms: { h1: "Epoxy Flooring Penampang untuk Rumah Teres & Renovation", intro: "Rumah di Penampang sering perlukan kemasan praktikal untuk bilik air, dapur dan garage. Dalam keadaan Sabah yang lembap, kami check moisture, jubin lama dan crack sebelum beri cadangan.", problemsTitle: "Masalah lantai rumah di Penampang", problems: ["Jubin lama nampak kusam selepas renovation", "Bilik air atau dapur mudah licin", "Kelembapan pada konkrit atau grout", "Garage susah dicuci selepas penggunaan harian"], systemTitle: "Cadangan untuk rumah di Penampang", system: "Epoxy flake dengan topcoat anti-slip sesuai dipertimbangkan untuk bilik air dan garage. Untuk ruang dalaman, sistem dan tahap kilat dipilih mengikut keadaan serta cara ruang digunakan.", price: "Anggaran RM28–RM32/kps, tertakluk pada saiz, keadaan jubin, moisture dan preparation.", faq: [{ q: "Epoxy sesuai untuk rumah teres di Penampang?", a: "Boleh, jika permukaan sesuai dan disediakan dengan betul. Kami check ruang dan kegunaan sebelum cadangkan sistem." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring in Penampang for Terrace Homes & Renovations", intro: "Homes in Penampang often need practical finishes for bathrooms, kitchens and garages. In Sabah’s humid conditions, we check moisture, old tiles and cracks before recommending a system.", problemsTitle: "Common home floor problems in Penampang", problems: ["Old tiles looking dull after renovation", "Slippery bathroom or kitchen areas", "Moisture around concrete or grout", "Garage floors that are difficult to clean"], systemTitle: "Recommended system for Penampang homes", system: "Epoxy flake with an anti-slip topcoat can suit bathrooms and garages. For interiors, the system and gloss level are selected based on floor condition and use.", price: "Estimated RM28–RM32/sqft, subject to size, tile condition, moisture and preparation.", faq: [{ q: "Is epoxy suitable for terrace houses in Penampang?", a: "It can be when the surface is suitable and properly prepared. We inspect the space and intended use before recommending a system." }, ...commonFaq.en] },
      zh: { h1: "Penampang 排屋与翻新环氧地坪", intro: "Penampang 的住宅常需要适合浴室、厨房和车库的实用地面。在沙巴潮湿环境下，我们会先检查湿度、旧瓷砖和裂缝。", problemsTitle: "Penampang 住宅常见地面问题", problems: ["翻新后旧瓷砖仍显得暗淡", "浴室或厨房容易打滑", "水泥地或砖缝潮湿", "车库地面难以清理"], systemTitle: "适合 Penampang 住宅的系统", system: "浴室和车库可考虑环氧彩片加防滑面漆。室内空间则根据地面情况和用途选择系统及亮度。", price: "估价约 RM28–RM32/平方尺，具体取决于面积、瓷砖情况、湿度和处理工作。", faq: [{ q: "环氧地坪适合 Penampang 排屋吗？", a: "如果表面适合并做好处理就可以。我们会先检查空间和用途，再建议系统。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flooring-inanam": {
    slug: "epoxy-flooring-inanam", area: "Inanam, Sabah", metaTitle: "Epoxy Flooring Inanam | FLEKS Epoxy Sabah", metaDescription: "Servis epoxy flooring Inanam untuk rumah, shoplot dan unit komersial. Sistem praktikal, tahan dan mudah dijaga.",
    content: {
      ms: { h1: "Epoxy Flooring Inanam untuk Rumah, Shoplot & Unit Komersial", intro: "Di Inanam, lantai shoplot dan unit komersial perlukan permukaan yang praktikal untuk kegunaan harian. Rumah pula perlukan kemasan yang senang dicuci tanpa abaikan keadaan lantai asal.", problemsTitle: "Masalah biasa di Inanam", problems: ["Lantai shoplot kusam dan banyak kesan", "Konkrit berhabuk atau permukaan tidak sekata", "Ruang kerja perlukan kemasan mudah dijaga", "Jubin rumah lama susah dicuci"], systemTitle: "Sistem praktikal untuk penggunaan harian", system: "Sistem solid epoxy atau epoxy flake boleh dipilih ikut trafik ruang. Topcoat ditentukan mengikut keperluan anti-slip, pembersihan dan ketahanan.", price: "Anggaran RM28–RM32/kps. Ruang komersial dengan repair atau preparation berat akan dinilai berasingan.", faq: [{ q: "Boleh buat epoxy untuk shoplot yang masih beroperasi?", a: "Jadual perlu dirancang ikut akses dan masa curing. Kami akan terangkan tempoh kerja selepas semakan tapak." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring in Inanam for Homes, Shoplots & Commercial Units", intro: "Shoplots and commercial units in Inanam need practical floors for daily use. Homes need easier cleaning without ignoring the condition of the existing surface.", problemsTitle: "Common floor issues in Inanam", problems: ["Dull shoplot floors with heavy marks", "Dusty concrete or uneven surfaces", "Work areas needing easier maintenance", "Old home tiles that are difficult to clean"], systemTitle: "Practical systems for daily use", system: "Solid epoxy or epoxy flake can be selected according to traffic. The topcoat is chosen for slip resistance, cleaning and durability needs.", price: "Estimated RM28–RM32/sqft. Commercial floors needing repairs or heavy preparation are assessed separately.", faq: [{ q: "Can epoxy be installed in an operating shoplot?", a: "Scheduling must account for access and curing time. We explain the work window after inspecting the site." }, ...commonFaq.en] },
      zh: { h1: "Inanam 住宅、店屋与商业单位环氧地坪", intro: "Inanam 的店屋和商业单位需要适合日常使用的实用地面。住宅则需要更容易清理，同时也要考虑原有地面的情况。", problemsTitle: "Inanam 常见地面问题", problems: ["店屋地面暗淡且有明显痕迹", "水泥地起灰或表面不平", "工作区需要更容易维护", "住宅旧瓷砖难清理"], systemTitle: "适合日常使用的系统", system: "可根据使用频率选择纯色环氧或环氧彩片。面漆则按防滑、清洁和耐用需求决定。", price: "估价约 RM28–RM32/平方尺。需要修补或大量地面处理的商业空间会另行评估。", faq: [{ q: "营业中的店屋可以施工吗？", a: "需要按照出入和固化时间安排。检查现场后，我们会说明适合的施工时段。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flooring-putatan": {
    slug: "epoxy-flooring-putatan", area: "Putatan, Sabah", metaTitle: "Epoxy Flooring Putatan | FLEKS Epoxy Sabah", metaDescription: "Epoxy flooring Putatan untuk rumah, bilik air dan garage dengan pilihan anti-slip serta permukaan lebih mudah dicuci.",
    content: {
      ms: { h1: "Epoxy Flooring Putatan untuk Rumah, Bilik Air & Garage", intro: "FLEKS membantu pemilik rumah di Putatan menilai lantai lama sebelum pilih kemasan. Fokus utama ialah preparation, pembersihan yang lebih mudah dan pilihan anti-slip untuk ruang yang sesuai.", problemsTitle: "Masalah lantai kediaman di Putatan", problems: ["Lantai bilik air licin bila basah", "Garage ada kotoran dan kesan tayar", "Jubin kusam atau warna tidak sekata", "Permukaan lembap atau ada crack kecil"], systemTitle: "Sistem untuk ruang kediaman", system: "Epoxy flake dan topcoat anti-slip sesuai dipertimbangkan untuk bilik air atau garage. Keadaan jubin, slope dan kelembapan perlu diperiksa terlebih dahulu.", price: "Anggaran RM28–RM32/kps selepas menilai saiz, repair dan sistem yang diperlukan.", faq: [{ q: "Ada pilihan anti-slip untuk bilik air?", a: "Ada. Tahap tekstur topcoat akan dicadangkan mengikut kawasan basah dan cara ruang digunakan." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring in Putatan for Homes, Bathrooms & Garages", intro: "FLEKS helps Putatan homeowners assess old floors before choosing a finish. The focus is correct preparation, easier cleaning and an anti-slip option where suitable.", problemsTitle: "Residential floor problems in Putatan", problems: ["Bathroom floors that become slippery when wet", "Garage floors with dirt and tyre marks", "Dull tiles or uneven colour", "Damp surfaces or small cracks"], systemTitle: "Systems for residential spaces", system: "Epoxy flake and an anti-slip topcoat may suit bathrooms or garages. Tile condition, slope and moisture must be checked first.", price: "Estimated RM28–RM32/sqft after assessing size, repairs and the required system.", faq: [{ q: "Is an anti-slip bathroom finish available?", a: "Yes. We recommend the topcoat texture based on the wet area and how the space is used." }, ...commonFaq.en] },
      zh: { h1: "Putatan 住宅、浴室与车库环氧地坪", intro: "FLEKS 帮助 Putatan 屋主先评估旧地面，再选择效果。重点是正确处理、更容易清洁，以及在适合的区域提供防滑选择。", problemsTitle: "Putatan 住宅常见地面问题", problems: ["浴室地面遇水容易打滑", "车库有污渍和轮胎痕迹", "瓷砖暗淡或颜色不均", "表面潮湿或有小裂缝"], systemTitle: "住宅空间系统", system: "浴室或车库可考虑环氧彩片和防滑面漆。施工前需要检查瓷砖、坡度和湿度。", price: "检查面积、修补和所需系统后，估价约 RM28–RM32/平方尺。", faq: [{ q: "浴室有防滑选择吗？", a: "有。我们会根据潮湿程度和空间用途建议面漆纹理。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flooring-likas": {
    slug: "epoxy-flooring-likas", area: "Likas, Sabah", metaTitle: "Epoxy Flooring Likas | FLEKS Epoxy Sabah", metaDescription: "Epoxy flooring Likas untuk renovation rumah, bilik air, dapur dan ruang komersial. Semakan lantai dan sebut harga jelas.",
    content: {
      ms: { h1: "Epoxy Flooring Likas untuk Renovation Rumah & Ruang Komersial", intro: "Untuk renovation di Likas, epoxy boleh dipertimbangkan bagi refresh bilik air, dapur, rumah atau ruang komersial. Kami check permukaan sedia ada supaya cadangan bukan sekadar ikut rupa.", problemsTitle: "Keadaan lantai yang perlu diperiksa", problems: ["Jubin lama bertompok atau grout gelap", "Dapur susah dicuci selepas memasak", "Lantai kedai perlukan rupa lebih kemas", "Permukaan sedia ada longgar atau lembap"], systemTitle: "Cadangan berdasarkan ruang", system: "Flake finish sesuai untuk menyamarkan variasi kecil dan memberi tekstur. Kemasan solid lebih ringkas untuk ruang komersial, tertakluk pada preparation yang diperlukan.", price: "Anggaran RM28–RM32/kps. Kami ukur dan terangkan skop preparation sebelum kerja bermula.", faq: [{ q: "Boleh refresh lantai dapur dengan epoxy?", a: "Boleh dipertimbangkan selepas kami check minyak, kelembapan, keadaan jubin dan keperluan pembersihan ruang." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring in Likas for Home Renovations & Commercial Spaces", intro: "For renovations in Likas, epoxy can refresh bathrooms, kitchens, homes or commercial spaces. We inspect the existing surface so the recommendation is based on more than appearance.", problemsTitle: "Floor conditions to inspect", problems: ["Patchy old tiles or dark grout", "Kitchen floors that are difficult to clean", "Shop floors needing a cleaner appearance", "Loose or damp existing surfaces"], systemTitle: "Recommendations based on the space", system: "Flake finishes can disguise minor variation and add texture. Solid finishes offer a simpler commercial look, subject to the required preparation.", price: "Estimated RM28–RM32/sqft. We measure and explain the preparation scope before work starts.", faq: [{ q: "Can epoxy refresh a kitchen floor?", a: "It can be considered after checking oil, moisture, tile condition and the cleaning needs of the space." }, ...commonFaq.en] },
      zh: { h1: "Likas 住宅翻新与商业空间环氧地坪", intro: "Likas 翻新项目可考虑用环氧地坪更新浴室、厨房、住宅或商业空间。我们会检查现有表面，让建议不只看外观。", problemsTitle: "需要检查的地面情况", problems: ["旧瓷砖有色差或砖缝发黑", "厨房地面难清理", "店铺需要更整洁的外观", "现有表面松动或潮湿"], systemTitle: "按空间建议系统", system: "彩片效果可遮盖轻微差异并增加纹理。商业空间可考虑简洁的纯色效果，但要先确认所需地面处理。", price: "估价约 RM28–RM32/平方尺。开工前我们会测量并说明地面处理范围。", faq: [{ q: "厨房地面可以用环氧更新吗？", a: "可以考虑，但要先检查油污、湿度、瓷砖情况和清洁需求。" }, ...commonFaq.zh] }
    }
  },
  "bathroom-epoxy-flooring-sabah": {
    slug: "bathroom-epoxy-flooring-sabah", area: "Sabah", metaTitle: "Bathroom Epoxy Flooring Sabah | Anti-Slip & Easy Clean", metaDescription: "Epoxy bilik air Sabah untuk jubin lama, pilihan topcoat anti-slip dan permukaan lebih mudah dicuci. Surface preparation diperiksa dahulu.",
    content: {
      ms: { h1: "Bathroom Epoxy Flooring Sabah dengan Pilihan Anti-Slip", intro: "Epoxy bilik air bukan sekadar tutup jubin lama. Kawasan basah perlukan semakan slope, kelembapan, grout, jubin longgar dan pilihan topcoat yang sesuai.", problemsTitle: "Masalah biasa lantai bilik air", problems: ["Jubin licin apabila basah", "Grout hitam dan susah dicuci", "Jubin lama kusam atau bercorak tidak sekata", "Kelembapan, bocor atau air bertakung"], systemTitle: "Sistem yang sesuai untuk kawasan basah", system: "Kami biasanya pertimbangkan primer, epoxy base, flake atau kemasan warna, kemudian topcoat anti-slip. Epoxy memberi permukaan lebih berterusan, tetapi punca bocor perlu dikenal pasti terlebih dahulu.", price: "Anggaran RM28–RM32/kps. Bilik air kecil mungkin tertakluk pada caj minimum kerana proses dan bahan tetap diperlukan.", faq: [{ q: "Epoxy akan buat bilik air kalis air terus?", a: "Epoxy memberi permukaan berterusan, tetapi ia bukan pengganti automatik untuk membaiki punca kebocoran atau waterproofing yang rosak. Kami perlu check dulu." }, ...commonFaq.ms] },
      en: { h1: "Bathroom Epoxy Flooring in Sabah with Anti-Slip Options", intro: "Bathroom epoxy is more than covering old tiles. Wet areas need checks for slope, moisture, grout, loose tiles and the right topcoat.", problemsTitle: "Common bathroom floor problems", problems: ["Tiles that become slippery when wet", "Dark grout that is difficult to clean", "Dull or mismatched old tiles", "Moisture, leaks or standing water"], systemTitle: "A suitable system for wet areas", system: "We typically consider primer, epoxy base, flake or colour finish, followed by an anti-slip topcoat. Epoxy provides a more continuous surface, but the source of leaks must be identified first.", price: "Estimated RM28–RM32/sqft. Small bathrooms may have a minimum charge because the full process and materials are still required.", faq: [{ q: "Will epoxy automatically waterproof my bathroom?", a: "Epoxy creates a more continuous surface, but it is not an automatic substitute for repairing a leak source or failed waterproofing. We need to inspect it first." }, ...commonFaq.en] },
      zh: { h1: "沙巴浴室环氧地坪与防滑选择", intro: "浴室环氧地坪不只是覆盖旧瓷砖。潮湿区域需要检查坡度、湿度、砖缝、松动瓷砖和合适的面漆。", problemsTitle: "浴室常见地面问题", problems: ["瓷砖遇水容易打滑", "砖缝发黑且难清理", "旧瓷砖暗淡或花色不统一", "潮湿、漏水或积水"], systemTitle: "适合潮湿区域的系统", system: "一般会考虑底漆、环氧底层、彩片或颜色效果，再加防滑面漆。环氧可形成更连续的表面，但必须先找出漏水原因。", price: "估价约 RM28–RM32/平方尺。小浴室仍需完整工序和材料，可能有最低收费。", faq: [{ q: "做环氧后浴室就一定不会漏水吗？", a: "环氧可形成更连续的表面，但不能自动代替修复漏水源或损坏的防水层。我们需要先检查。" }, ...commonFaq.zh] }
    }
  },
  "commercial-epoxy-flooring-kk": {
    slug: "commercial-epoxy-flooring-kk", area: "Kota Kinabalu, Sabah", metaTitle: "Commercial Epoxy Flooring KK | FLEKS Epoxy Sabah", metaDescription: "Commercial epoxy flooring di Kota Kinabalu untuk kedai, cafe, showroom dan office. Mudah dijaga dengan sistem ikut trafik ruang.",
    content: {
      ms: { h1: "Commercial Epoxy Flooring KK untuk Kedai, Cafe & Showroom", intro: "Lantai komersial perlu tahan penggunaan harian dan mudah dijaga. Kami nilai trafik, jadual operasi, keadaan konkrit serta tahap anti-slip sebelum cadangkan sistem.", problemsTitle: "Cabaran ruang komersial", problems: ["Trafik pelanggan buat lantai cepat kusam", "Kesan tumpahan di cafe atau kedai", "Konkrit berhabuk di unit baru", "Masa kerja perlu ikut jadual operasi"], systemTitle: "Sistem ikut trafik dan kegunaan", system: "Solid epoxy atau flake system boleh dipilih untuk kedai, cafe, showroom dan office. Topcoat disesuaikan dengan trafik, pembersihan dan tahap kilat yang dikehendaki.", price: "Anggaran RM32/kps untuk banyak ruang komersial, tetapi skop sebenar ikut size, repair, preparation dan jadual kerja.", faq: [{ q: "Boleh buat kerja selepas waktu operasi?", a: "Boleh dibincangkan. Jadual bergantung pada akses, bunyi semasa preparation dan masa curing sebelum ruang boleh digunakan." }, ...commonFaq.ms] },
      en: { h1: "Commercial Epoxy Flooring in KK for Shops, Cafes & Showrooms", intro: "Commercial floors need to handle daily use and remain practical to maintain. We assess traffic, operating hours, concrete condition and slip resistance before recommending a system.", problemsTitle: "Commercial flooring challenges", problems: ["Customer traffic causing dull surfaces", "Spills in cafes or shops", "Dusty concrete in new units", "Installation timing around operations"], systemTitle: "Systems based on traffic and use", system: "Solid epoxy or flake systems can suit shops, cafes, showrooms and offices. The topcoat is selected for traffic, cleaning and the preferred sheen.", price: "Many commercial spaces are estimated around RM32/sqft, but the actual scope depends on size, repairs, preparation and scheduling.", faq: [{ q: "Can work be scheduled after operating hours?", a: "This can be discussed. Scheduling depends on access, preparation noise and curing time before the space can reopen." }, ...commonFaq.en] },
      zh: { h1: "亚庇店铺、咖啡店与展厅商业环氧地坪", intro: "商业地面需要应付日常使用，也要容易维护。建议系统前，我们会评估人流、营业时间、水泥地情况和防滑需求。", problemsTitle: "商业空间地面挑战", problems: ["客流让地面快速暗淡", "咖啡店或店铺有液体污渍", "新单位水泥地起灰", "施工时间需要配合营业安排"], systemTitle: "按人流与用途选择系统", system: "店铺、咖啡店、展厅和办公室可选择纯色环氧或彩片系统。面漆按人流、清洁和所需亮度决定。", price: "许多商业空间估价约 RM32/平方尺，但实际范围取决于面积、修补、地面处理和施工时间。", faq: [{ q: "可以安排在营业时间后施工吗？", a: "可以讨论。时间安排取决于出入、地面处理噪音和重新开放前的固化时间。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flake-flooring-sabah": {
    slug: "epoxy-flake-flooring-sabah", area: "Sabah", metaTitle: "Epoxy Flake Flooring Sabah | FLEKS Epoxy", metaDescription: "Epoxy flake flooring Sabah untuk garage, bilik air dan ruang komersial dengan pilihan tekstur dan topcoat anti-slip.",
    content: {
      ms: { h1: "Epoxy Flake Flooring Sabah untuk Garage, Bilik Air & Komersial", intro: "Flake finish memberi rupa bertekstur dan membantu menyamarkan variasi kecil pada permukaan. Saiz flake, warna dan topcoat perlu dipilih ikut ruang, bukan ikut gambar sahaja.", problemsTitle: "Bila flake system sesuai", problems: ["Mahukan rupa bertekstur, bukan warna rata", "Perlu pilihan anti-slip untuk kawasan tertentu", "Lantai ada variasi warna kecil", "Ruang perlukan kemasan mudah dijaga"], systemTitle: "Bagaimana flake system dibina", system: "Selepas preparation dan primer, epoxy base disapu sebelum flake ditabur. Lebihan flake diratakan dan ditutup dengan topcoat mengikut tahap tekstur, kilat dan ketahanan yang diperlukan.", price: "Anggaran RM28–RM32/kps bergantung pada coverage flake, topcoat, preparation dan saiz ruang.", faq: [{ q: "Epoxy flake mesti kasar ka?", a: "Tidak semestinya. Tekstur akhir bergantung pada saiz flake, cara finishing dan topcoat. Untuk kawasan basah, tahap anti-slip perlu diseimbangkan dengan kemudahan cuci." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flake Flooring in Sabah for Garages, Bathrooms & Commercial Spaces", intro: "Flake finishes add texture and help disguise small surface variations. Flake size, colour and topcoat should be selected for the space rather than from an image alone.", problemsTitle: "When a flake system fits", problems: ["A textured look rather than a flat colour", "An anti-slip option for selected areas", "Minor colour variation in the floor", "A surface that is easier to maintain"], systemTitle: "How a flake system is built", system: "After preparation and primer, an epoxy base is applied before flakes are broadcast. Excess flakes are levelled and sealed with a topcoat selected for texture, sheen and durability.", price: "Estimated RM28–RM32/sqft depending on flake coverage, topcoat, preparation and space size.", faq: [{ q: "Does epoxy flake always feel rough?", a: "Not necessarily. Final texture depends on flake size, finishing and topcoat. Wet areas need a balance between slip resistance and cleaning." }, ...commonFaq.en] },
      zh: { h1: "沙巴车库、浴室与商业空间环氧彩片地坪", intro: "彩片效果增加纹理，也能遮盖轻微的表面色差。彩片大小、颜色和面漆应按空间选择，不能只看图片。", problemsTitle: "适合彩片系统的情况", problems: ["想要有纹理而不是单一颜色", "部分区域需要防滑选择", "地面有轻微色差", "需要更容易维护的表面"], systemTitle: "彩片系统施工方式", system: "地面处理和底漆完成后，先施工环氧底层，再撒彩片。多余彩片处理后，按纹理、亮度和耐用需求加面漆。", price: "估价约 RM28–RM32/平方尺，取决于彩片覆盖、面漆、地面处理和面积。", faq: [{ q: "环氧彩片一定很粗吗？", a: "不一定。最终纹理取决于彩片大小、处理方式和面漆。潮湿区域要平衡防滑与清洁。" }, ...commonFaq.zh] }
    }
  },
  "epoxy-flooring-price-sabah": {
    slug: "epoxy-flooring-price-sabah", area: "Sabah", metaTitle: "Epoxy Flooring Price Sabah | FLEKS Epoxy", metaDescription: "Anggaran harga epoxy flooring Sabah RM28–RM32/kps. Ketahui faktor saiz, keadaan lantai, preparation, sistem dan finishing.",
    content: {
      ms: { h1: "Harga Epoxy Flooring Sabah: Anggaran RM28–RM32/kps", intro: "Harga epoxy tidak boleh dinilai daripada keluasan sahaja. Keadaan lantai, kelembapan, repair, jenis sistem dan finishing menentukan skop sebenar.", problemsTitle: "Apa yang mempengaruhi harga", problems: ["Jumlah keluasan dan bentuk ruang", "Jubin, konkrit, crack atau kelembapan", "Tahap grinding dan surface preparation", "Flake coverage, topcoat dan pilihan anti-slip"], systemTitle: "Cara kami beri anggaran", system: "Anda boleh hantar gambar dan saiz awal melalui WhatsApp. Untuk sebut harga jelas, kami buat lawatan tapak, ukur ruang dan terangkan preparation serta sistem yang dicadangkan.", price: "Anggaran laman ialah RM28–RM32/kps. Sebut harga akhir diberi sebelum kerja bermula dan boleh berubah jika repair tambahan diperlukan.", faq: [{ q: "Kenapa harga per kaki persegi boleh berbeza?", a: "Dua lantai dengan saiz sama boleh perlukan preparation berbeza. Kelembapan, crack, jubin longgar, topcoat dan akses kerja mempengaruhi kos." }, ...commonFaq.ms] },
      en: { h1: "Epoxy Flooring Price in Sabah: RM28–RM32/sqft Estimate", intro: "Epoxy pricing cannot be assessed by area alone. Floor condition, moisture, repairs, system type and finish determine the actual scope.", problemsTitle: "What affects epoxy flooring price", problems: ["Total area and room shape", "Tiles, concrete, cracks or moisture", "Grinding and surface preparation required", "Flake coverage, topcoat and anti-slip option"], systemTitle: "How we prepare an estimate", system: "You can send initial photos and size through WhatsApp. For a clear quotation, we visit the site, measure the space and explain the preparation and recommended system.", price: "The website estimate is RM28–RM32/sqft. A final quote is provided before work starts and may change if additional repairs are needed.", faq: [{ q: "Why can the square-foot rate vary?", a: "Two floors of the same size can need very different preparation. Moisture, cracks, loose tiles, topcoat and site access affect cost." }, ...commonFaq.en] },
      zh: { h1: "沙巴环氧地坪价格：约 RM28–RM32/平方尺", intro: "环氧地坪不能只按面积估价。地面情况、湿度、修补、系统类型和效果都会影响实际工程范围。", problemsTitle: "影响价格的因素", problems: ["总面积和空间形状", "瓷砖、水泥地、裂缝或湿度", "打磨和地面处理程度", "彩片覆盖、面漆和防滑选择"], systemTitle: "我们如何提供估价", system: "您可以先通过 WhatsApp 发送照片和面积。为了提供清楚报价，我们会上门测量，并说明地面处理和建议系统。", price: "网站估价为 RM28–RM32/平方尺。开工前会提供最终报价，如需额外修补，价格可能调整。", faq: [{ q: "为什么每平方尺价格会不同？", a: "同样面积的地面可能需要完全不同的处理。湿度、裂缝、松动瓷砖、面漆和现场出入都会影响成本。" }, ...commonFaq.zh] }
    }
  }
};

export function pageMetadata(page) {
  return { title: page.metaTitle, description: page.metaDescription, alternates: { canonical: `/${page.slug}` }, openGraph: { title: page.metaTitle, description: page.metaDescription, url: `/${page.slug}`, type: "website" } };
}
