export const en = {
  header: { process: "Process", gallery: "Finishes", pricing: "Pricing", faq: "FAQ", areas: "Areas", btnBook: "Book Free Site Visit", wa: "WhatsApp Us", waMsg: "Hi FLEKS, I would like to ask about epoxy flooring in Sabah." },
  hero: { badge: "Epoxy flooring service · Kota Kinabalu & nearby Sabah", title: "Old floors that are slippery, stained or hard to clean?", subtitle: "We inspect the floor condition before recommending an epoxy system for your home, bathroom, garage, shop or commercial space.", btnBook: "Book Free Site Visit", btnWa: "WhatsApp Us", imageLabel: "Finish Idea", imageNote: "Finishing reference only. Actual results depend on the floor condition and selected system." },
  trustBar: ["Free Site Visit", "Local Sabah Team", "Clear Quotation", "Anti-Slip Option", "RM28–RM32/sqft Estimate"],
  localTeam: { eyebrow: "Local team, clear process", title: "Local Sabah Team", intro: "FLEKS is run by a local team in Kota Kinabalu. During each site visit, we check the floor condition, measure the actual size, explain suitable finishing options, and provide a clear quotation before work begins.", cards: [
    { title: "Free Site Visit", text: "We inspect the floor condition before recommending the right epoxy system." },
    { title: "Clear Pricing Before Work", text: "No hidden charges. You know the estimated cost before the job starts." },
    { title: "Surface Preparation First", text: "Long-lasting epoxy starts with proper floor preparation." }
  ] },
  problem: { eyebrow: "Before choosing a finish", title: "We start with the floor problem", body: "Epoxy flooring can create a cleaner, easier-to-maintain surface for homes, bathrooms, garages, shops and commercial spaces. Before work starts, we inspect the floor so the recommended system fits your space.", problems: ["Old tiles that are slippery or stained", "Marks that are difficult to clean", "Cracks, moisture or uneven surfaces", "Wet areas that need slip resistance"], checkTitle: "What FLEKS checks", checks: ["Existing surface type", "Moisture and cracks", "Space size and intended use", "Primer, finish and topcoat options"] },
  process: { eyebrow: "Installation process", title: "How We Apply Epoxy So It Lasts Longer", intro: "Many epoxy problems come from poor surface preparation. That is why we focus on floor condition, moisture, primer and the right topcoat.", steps: [
    { title: "Floor Condition Check", text: "We check tiles, concrete, moisture, cracks and slippery areas." },
    { title: "Clean & Prepare Surface", text: "The surface is cleaned, roughened or prepared so epoxy can bond properly." },
    { title: "Primer Coat", text: "Primer helps create a stronger bond between the existing surface and epoxy layer." },
    { title: "Epoxy Base + Flake / Finish", text: "We select a system for the space: bathroom, home, garage, shop or commercial area." },
    { title: "Anti-Slip / Glossy Topcoat", text: "The final layer improves durability, cleaning and slip resistance." },
    { title: "Final Inspection", text: "We inspect the finished work before handover." }
  ] },
  gallery: { eyebrow: "Finish references", title: "Choose a finish with clear expectations", subtitle: "The images below are finish ideas, not claims of completed FLEKS projects. We show samples and recommend a system after inspecting your floor.", ideaLabel: "Finish Idea", note: "A finishing idea for customer reference. Actual results depend on floor condition, space size and the selected epoxy system.", locationLabel: "Suitable for", systemLabel: "Suggested system", items: [
    { title: "White flake", space: "Bathrooms & wet areas", system: "Epoxy flake + anti-slip topcoat", alt: "Anti-slip white epoxy flake finish idea for bathroom" },
    { title: "Teal metallic", space: "Showrooms & interiors", system: "Metallic epoxy + glossy topcoat", alt: "Teal metallic epoxy finish idea for interior space" },
    { title: "Coffee flake", space: "Bathrooms & utility areas", system: "Epoxy flake + textured topcoat", alt: "Coffee flake epoxy finish idea for bathroom" },
    { title: "Silver flake", space: "Garages & work areas", system: "Epoxy flake + durable topcoat", alt: "Silver flake epoxy finish idea for garage" },
    { title: "Pearl grey", space: "Homes & shops", system: "Coloured epoxy + glossy topcoat", alt: "Pearl grey epoxy finish idea for home" },
    { title: "Solid grey", space: "Commercial & wet areas", system: "Solid epoxy + anti-slip topcoat", alt: "Solid grey anti-slip epoxy finish idea" }
  ] },
  pricing: { eyebrow: "Initial estimate", title: "Pricing depends on your floor condition", subtitle: "A typical estimate is RM28–RM32/sqft. Final pricing depends on size, preparation, system and selected finish.", range: "RM28–RM32", unit: "/sqft", points: ["Free site visit", "System recommendation for your space", "Clear quote before work", "No hidden charges"], note: "Damp, cracked or damaged floors may require extra repair and will be assessed during the site visit.", btnBook: "Book Free Site Visit" },
  offer: { eyebrow: "Selected projects", title: "Introductory Pricing for Selected Projects in Sabah", body: "For selected projects in Kota Kinabalu and around Sabah, FLEKS offers introductory pricing with a free site visit, suitable epoxy system recommendation, and a clear quotation before work begins.", note: "Send 1–3 floor photos through WhatsApp after submitting so we can give a more accurate recommendation." },
  booking: { eyebrow: "Free site visit", title: "Let us inspect your floor first", subtitle: "Share a few details. WhatsApp will open with a complete message so we can arrange your visit.", serviceLabel: "Space type", services: ["Home", "Bathroom", "Garage", "Shop", "Commercial"], nameLabel: "Name", namePh: "Your name", locationLabel: "Location", locationPh: "Example: Penampang, Sabah", sizeLabel: "Estimated size", sizePh: "Example: 120 sqft", issueLabel: "Floor issue", issues: ["Slippery", "Dull / stained", "Hard to clean", "Cracked", "Leaking / damp", "Want a more premium look", "Not sure, need FLEKS to check"], dateLabel: "Preferred date", btnSubmit: "Book Free Site Visit", helper: "Tip: Send 1–3 floor photos through WhatsApp after submitting so we can recommend the right finish and estimate more accurately.", alertName: "Please enter your name.", alertLocation: "Please enter the project location.", flexible: "Flexible / not selected", message: { intro: "Hi FLEKS, I would like to book a free site visit.", name: "Name", location: "Location", space: "Space type", size: "Estimated size", issue: "Floor issue", date: "Preferred date", photos: "I will send floor photos after this message." } },
  faq: { eyebrow: "Common questions", title: "Epoxy Flooring FAQ — Sabah", subtitle: "Straight answers before you book a site visit.", items: [
    { q: "How much does epoxy flooring cost in Sabah?", a: "A typical estimate is around RM28–RM32/sqft, depending on area size, floor condition, epoxy system and finish. We provide a clear quote after inspection." },
    { q: "Is epoxy suitable for bathrooms?", a: "It can be, depending on the surface and selected system. For wet areas, proper preparation and an anti-slip topcoat are important." },
    { q: "Why does epoxy flooring peel?", a: "Common causes include poor preparation, moisture, dust, oil or a surface that is too smooth. We inspect and prepare the floor before applying epoxy." },
    { q: "How long does installation take?", a: "Most small spaces take around 2–3 days, depending on size, floor condition and selected finish." },
    { q: "Do old tiles need to be removed?", a: "Not always. We first inspect the existing tiles or floor before recommending the right preparation method." }
  ] },
  related: { eyebrow: "Areas & services", title: "Epoxy Flooring Services Around Sabah", subtitle: "Read a guide for your location or type of space.", label: "View guide" },
  thanks: { eyebrow: "Next step", title: "Your WhatsApp message is ready", body: "Send the open message so the FLEKS team can review your site visit details.", steps: ["Send the WhatsApp message", "Add 1–3 floor photos", "We arrange a site visit time"], wa: "Open WhatsApp", back: "Back to homepage" },
  footer: { desc: "Epoxy flooring for homes, bathrooms, garages, shops and commercial spaces in Kota Kinabalu and nearby Sabah.", quickLinks: "Links", services: "Service areas", contact: "Contact", rights: "All rights reserved.", honesty: "Free site visit · Clear quotation" }
};
